### ISSUE TITLE
[bug]: undefined array key "config" in Moduleadmin.class.php

### ISSUE THREAD

**Issue by billsimon** [FreePBX/framework#113]
### FreePBX Version

FreePBX 17

### Issue Description

Working at the console with fwconsole, commands `fwconsole ma list` and `fwconsole ma listonline` produce error,

```
In Moduleadmin.class.php line 1248:
                                
  Undefined array key "config"  
```

https://github.com/FreePBX/framework/blob/release/17.0/amp_conf/htdocs/admin/libraries/Console/Moduleadmin.class.php#L1247-L1248

$sig could be `false` ; code does not check that $sig is an array before referencing array key.                          

### Operating Environment

Deb 12
FreePBX 17.0.15.5

**Comment by jissphilip** [comment]
framework 17.0.15.7

**Comment by jissphilip** [comment]
HI @billsimon , 
Please test with framework 17.0.15.7 and let us know  the status 
Thanks
