### ISSUE TITLE
[bug]: php-asmanager.php Status($channel=null,$actionid=NULL) wont return single channel

### ISSUE THREAD

**Issue by awillemsls** [FreePBX/framework#120]
### FreePBX Version

FreePBX 16

### Issue Description

function Status($channel=null,$actionid=NULL)  will not be able to pull passed channel because its referencing $queue that isn't event set inside the function. https://github.com/FreePBX/framework/blob/dba21b94f6259523e491960b7fe3568ec63b54d6/amp_conf/htdocs/admin/libraries/php-asmanager.php#L1395
$parameters['Channel'] = $queue;  should be $parameters['Channel'] = $channel;

### Operating Environment

[release/17.0.15.14](https://github.com/FreePBX/framework/releases/tag/release%2F17.0.15.14)

### Relevant log output

```shell
I believe the description is enough. Calling it normally gets you all the channels like coreshowchannels if you pass a single channels it will still return all channels because the parameter is not getting set.
```

**Comment by kapilgupta01** [comment]
Hi @awillemsls Thank you for reporting this issue, pushed the fix to the Framework v17.0.15.15

Regards
Kapil
