### ISSUE TITLE
[bug]: The version_compare_freepbx() in Moduleadmin.class.php doesn't check for an upgrade, just a difference

### ISSUE THREAD

**Issue by Stevehans** [FreePBX/framework#125]
### FreePBX Version

FreePBX 16

### Issue Description

For modules with an "updateurl", the version_compare_freepbx() call in getUpgradableModules() isn't checking that the result is <0, this results in modules downgrading and is different from the same action in the GUI.

### Operating Environment

FreePBX 16.0.40.7

### Relevant log output

```shell
fwconsole ma showupgrades
No repos specified, using: [standard,extended,unsupported,commercial,unknown] from last GUI settings

Upgradable:
+---------------+---------------+----------------+
| Module        | Local Version | Online Version |
+---------------+---------------+----------------+
| threadsclient | 0.3           | 0.2            |
+---------------+---------------+----------------+
```

**Comment by kapilgupta01** [comment]
"threadsclient " is this module coming from Freepbx mirror server or is this your own server @Stevehans ?

**Comment by Stevehans** [comment]
It's our own server, I'd left l a lower version in the json, the GUI check didn't think it was upgradable, but the overnight auto update downgraded it.

**Comment by Stevehans** [comment]
code is
`if (version_compare_freepbx($module['version'], $module_update_data['version'])) {`

should be

`if (version_compare_freepbx($module['version'], $module_update_data['version']) < 0) {`

**Comment by kapilgupta01** [comment]
Hi @Stevehans can you please raise PR to submit your fixes to the framework module? 

Thanks

**Comment by Stevehans** [comment]
Will do

**Comment by Stevehans** [comment]
Done with #126

**Comment by kapilgupta01** [comment]
Thanks a lot @Stevehans for your contribution, will be available in next framework release.
