### ISSUE TITLE
[bug]: What's the correct way to request later versions of composer packages be upgraded within framework?

### ISSUE THREAD

**Issue by Stevehans** [FreePBX/framework#133]
### FreePBX Version

FreePBX 16

### Issue Description

I've hit issues which are fixed in later versions of packages (for instance, the bug in fightbulc/moment was fixed 6 years ago in 1.28).

Is this a pull request or does it need wider consideration?

Likewise, I've hit an issue in the bootstrap tables, which is also fixed in a newer version of the JavaScript library, so I'd also like to request the most recent version of this?

Looking for guidance!

### Operating Environment

FreePBX 16.0.40.8

**Comment by kapilgupta01** [comment]
Hi @Stevehans please try with Freepbx 17 which has all the latest libs. Do not try to upgrade 16 to the latest composer/libs otherwise you may get lots of dependencies error, better to use Freepbx 17.

**Comment by Stevehans** [comment]
Unfortunately our module needs to support both 16 and 17, and I can't see people upgrading until 17 is solid and stable.

At present I'm shipping our own copies of a few composer packages.

I'll check what the dependencies are and see what the impact would be.

But if there are no other dependencies, are you open to upgrading some specific packages within the 16 framework?

**Comment by kapilgupta01** [comment]
Hey @Stevehans we are not going to touch 16 now which is pretty stable.
