### ISSUE TITLE
17 isn't catching the json_decode() exception that is thrown

### ISSUE THREAD

**Issue by Stevehans** [FreePBX/framework#135]
### FreePBX Version

FreePBX 17

### Issue Description

If the webserver returns invalid JSON (or say a 404), then the exception thrown by JSON_THROW_ON_ERROR isn't caught.

This is in page.modules.php around line 116

Needs a try ... catch

### Operating Environment

Latest 17 version, Asterisk 21

**Comment by kapilgupta01** [comment]
Thanks @Stevehans updated the 17 framework module.
