### ISSUE TITLE
The IonCube decoder on 16 won't decode the lowest level of encoding for 17

### ISSUE THREAD

**Issue by Stevehans** [FreePBX/framework#136]
### FreePBX Version

FreePBX 17

### Issue Description

Would it be possible to update the decoders on FreePBX 16 so we can ship a single module for both 16 and 17?

### Operating Environment

Freepbx 16 and 17

**Comment by Stevehans** [comment]
I'll check the versions and see what the overlap would be.

**Comment by kapilgupta01** [comment]
Hey @Stevehans We are not going to touch Freepbx 16 libraries as that's pretty stable.  Freepbx 17 has everything latest so I suggest you to please try 17. 
thanks

**Comment by Stevehans** [comment]
Is there a solution for cross version ioncube compatibility though?



Sent from my Galaxy



-------- Original message --------
From: kguptasangoma ***@***.***>
Date: 11/06/2024 17:41 (GMT+00:00)
To: FreePBX/framework ***@***.***>
Cc: Steve Hanselman ***@***.***>, Mention ***@***.***>
Subject: Re: [FreePBX/framework] The IonCube decoder on 16 won't decode the lowest level of encoding for 17 (Issue #136)


Hey @Stevehans<https://github.com/Stevehans> We are not going to touch Freepbx 16 libraries as that's pretty stable. Freepbx 17 has everything latest so I suggest you to please try 17.
thanks

**Comment by kapilgupta01** [comment]
ioncube runs along with the php version so if you are running freepbx 16 then you need php 7.4 supported ioncube lib.

**Comment by Stevehans** [comment]
For anyone that needs to do this, the solution is IonCube's ability to bundle.

You can encode a bundle with the 74 encoder, then add the exact same code tree (or a different code tree with v8 specific changes if you wish) to the same output with --add-to-bundle using the 82 encoder.

You then get a single installable module which will correctly load on FreePBX 16 with IonCube 10/PHP 7.4  and FreePBX 17 with IonCube 13/PHP 8.2
