### ISSUE TITLE
[bug]: We see 'Cannot load the ionCube PHP Loader - it was already loaded' Everywhere.

### ISSUE THREAD

**Issue by danardf** [FreePBX/framework#141]
### FreePBX Version

FreePBX 17

### Issue Description

We can see 'Cannot load the ionCube PHP Loader - it was already loaded' everywhere, for example on fwconsole r, fwconsole ma updateall... etc.
Maybe it's acceptable, but it's not on backup / restore module. 
When a backup is performed, we can see and error cosed by 'Cannot load the ionCube PHP Loader - it was already loaded' at the end of the backup process.

### Operating Environment

```
# fwconsole ma list | grep frame
Cannot load the ionCube PHP Loader - it was already loaded
| framework           | 17.0.17   | Enabled                           | GPLv2+      | Sangoma   |
```

### Relevant log output

```shell
Cannot load the ionCube PHP Loader - it was already loaded
```

**Comment by kapilgupta01** [comment]
Hey @danardf try with below comment - 

https://github.com/FreePBX/issue-tracker/issues/107#issuecomment-2082798296

**Comment by kapilgupta01** [comment]
Hey @danardf did you tried the steps i mentioned in my previous comment?

**Comment by danardf** [comment]
@kguptasangoma Hi Kapil
Yes, I answered you here: https://github.com/FreePBX/issue-tracker/issues/107#issuecomment-2082798296
