### ISSUE TITLE
[bug]: form_helper.php - form_prep if $str is null in htmlspecialchars (deprecated since php 8.1)

### ISSUE THREAD

**Issue by inferno-cc** [FreePBX/framework#149]
### FreePBX Version

FreePBX 17

### Issue Description

admin/helpers/form_helper.php - function form_prep uses htmlspecialchars on $str, but if $str is null it's throwing an error because htmlspecialchars on NULL is deprecated since php 8.1

### Operating Environment

Framework module version 17.0.19.1

**Comment by kapilgupta01** [comment]
framework v17.0.19.4
