### ISSUE TITLE
Incorrect comment or functionality in amp password creation

### ISSUE THREAD

**Issue by EC-Joe** [FreePBX/framework#3]
https://github.com/FreePBX/framework/blob/92e3674f731cd33ec0dabe1944677f597d136d8e/amp_conf/htdocs/admin/libraries/view.functions.php#L507-L509

The comment indicates that it will sha1 any password which is LESS THAN 40 characters that isn't a hex value. However, the preg match is actually looking for anything that is EXACTLY 40 characters, and is a hex value of lower case. Not sure if the comment is incorrect or the functionality.

http://3v4l.org/7Fckv

**Comment by EC-Joe** [comment]
Also I'm not positive on this one, but if someone actually did have a password of 40 0's, then I don't think they would actually be able to authenticate using it because when they try to auth it would attempt to sha1 their password of 40 0s which would never return true on the checkPassword function

https://github.com/FreePBX/framework/blob/92e3674f731cd33ec0dabe1944677f597d136d8e/amp_conf/htdocs/admin/libraries/gui_auth.php

Haven't tested this out but in theory that seems right?

**Comment by tm1000** [comment]
Please report issues to the proper location http://issues.freepbx.org.

Im disabling issues here.
