### ISSUE TITLE
[bug]: openpgp keyserver is invalid

### ISSUE THREAD

**Issue by Massi-X** [FreePBX/framework#96]
### FreePBX Version

FreePBX 16

### Issue Description

Hi to all, I recently came up with an issue with some modules containing a public key that isn't on the system were marked as invalid. The problem is this:
The key is trusted but not present on the system so the GPG class (libraries/BMO/GPG.class.php) tries to download the new key (`function checkSig()`) but this fails because the first keyserver defined is hkp://keys.openpgp.org that does not contain the user-id field (see https://superuser.com/a/1485255). The issue is fixed by changing the order of the servers so the keyserver array looks like this:
```
private $keyservers = array(
  "hkp://keyserver.ubuntu.com:80",  // This is in case port 11371 is blocked outbound
  "hkp://keys.openpgp.org", 
  "pgp.mit.edu", // Other random keyservers
  "keyserver.pgp.com"  // Other random keyserver
); // Yes. sks is there twice.
```

As an alternative, opengpg could be moved at the last position, if everything else fails.

Again this affect the file present in /var/www/html/admin/modules/libraries/BMO/GPG.class.php

### Operating Environment

FreePBX 16 - CentOS but it really doesn't matter

**Comment by kapilgupta01** [comment]
Hi @Massi-X could you please raise the PR with this fix ? Thanks

**Comment by Massi-X** [comment]
Yep @kguptasangoma but I don't know where to find the file, this is the reason I didn't do it. Could you point me in the right direction?

**Comment by miken32** [comment]
I have numerous signed third party modules on my PBXs that have no problems. The whole GPG infrastructure is kind of broken and nobody at Sangoma seems to have an idea for an alternative. Have you tried just importing the key? `sudo -u asterisk gpg --keyserver keyserver.ubuntu.com --recv-keys xxxxxxxx`

**Comment by miken32** [comment]
Also the answer says users can opt in to having their user IDs added at keys.openpgp.org. Surely the easiest fix is for your module developer to do this?

**Comment by Massi-X** [comment]
@miken32 Yep it works even automatically. I only removed the openpgp server which is broken and left Ubuntu as first and now everything works fine.

Edit: Yes this is possible but isn't it better to switch to Ubuntu as the default one so that it is not necessary for this manual step by developers?

**Comment by Massi-X** [comment]
Closing as seems to be more a setup issue with module developer or the specific distribution.
For anyone wondering: Make sure to confirm your email on openpgp server
